typography_spectrum: 0.14439671277068555
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.5839711888693273
  lightness: 0.056368461111560464
  saturation: 0.43904576427303255
  rhythmicContrast: 0.9272211682982743
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6694164138752967
analytics:
  google: null
  facebook: null
  twitter: null
name: 6IX DEGREES OF SEPARATION
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 6IX DEGREES
description: Story
purpose: []
