layout_spectrum: 0.6694164138752967
typography_spectrum: 0.6829553805291653
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.5839711888693273
  lightness: 0.056368461111560464
  saturation: 0.43904576427303255
  rhythmicContrast: 0.9272211682982743
name: 6IX DEGREES OF SEPARATION
favicon: null
title: 6IX DEGREES
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
