layout_spectrum: 0.89889344596304
typography_spectrum: 0.045166597003117204
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.0723305931314826
  lightness: 0.12937993998639286
  saturation: 0.7281864369288087
  rhythmicContrast: 0.11975157749839127
name: 6IX DEGREES OF SEPARATION
favicon: null
title: 6IX DEGREES
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
